### PR TITLE
Fix some typos in content19.html

### PR DESCRIPTION
**Pull request by cormullion**
some typos

### CODE REVIEW

**Comment by cormullion** [comment]
@ViralBShah oops I think I should have made this PR against `src` rather than `master`. (Not very good with Jekyll, sorry...😕)

**Comment by xorJane** [comment]
Thanks @cormullion!

**Comment by cormullion** [comment]
@xorJane 😀 sorry about the poorly-focused PR :)

**Comment by xorJane** [comment]
No, it was helpful!

**Pull request merged**
