### PR TITLE
Update social media buttons

### LINKED ISSUE #467: JuliaCon 2024: Social Media links
We have only Twitter and LinkedIn. 

Can we change the icon of Twitter?
Can we add other relevant social media channels? Slack, Discord, Discourse, Instagram, ....

### PR DESCRIPTION
**Pull request by pabloferz**
Closes #467

### CODE REVIEW

**Review by rayegun — APPROVED** [review]

**Comment by bvdmitri** [comment]
This breaks the layout on phones 

image

image

**Comment by bvdmitri** [comment]
In addition to the previous one the buttons are not centered anymore 
image

**Comment by pabloferz** [comment]
OK. The formatting issues are fixed now. Should be good to go.

**Comment by bvdmitri** [comment]
Thanks @pabloferz !

**Pull request merged**
