### PR TITLE
Eindhoven dining info

### PR DESCRIPTION
**Pull request by el-oso**
## Checklist for merge
- [x] I built the website locally and tested it using `Franklin.serve()`
- [x] All CI checks have passed and you have tested the online version (click on the list of checks and click `Build and Deploy / Preview` to see the preview)
- [ ] Somebody else reviewed my changes (use your best judgement if you need to merge quickly

## After merge
- [ ] Closed relevant issues

### CODE REVIEW

**Review by cormullion — COMMENTED** [review]
“dining” rather than “dinning” 😀

**Comment by bvdmitri** [comment]
@cormullion can we merge?

**Comment by cormullion** [comment]
Of course! (I learnt today that "dinning" is Dutch for "dining" 😀

**Comment by el-oso** [comment]
@cormullion ... except ... that I am not Dutch :sweat_smile:

**Pull request merged**
