### PR TITLE
Use a different photo for the community highlight

### PR DESCRIPTION
**Pull request by bvdmitri**
## Briefly Describe your changes

This PR changes the photo for the "Passionate Community" and moves the previous photo to the volunteer section

## Checklist for merge
- [x] I built the website locally and tested it using `Franklin.serve()`
- [ ] All CI checks have passed and you have tested the online version (click on the list of checks and click `Build and Deploy / Preview` to see the preview)
- [ ] Somebody else reviewed my changes (use your best judgement if you need to merge quickly

## After merge
- [ ] Closed relevant issues

### CODE REVIEW

**Comment by KeithWM** [comment]
To me the new photo seems very anonymous and nowhere near as good in exposing how passionate the local team are about Julia (and related events). I also don't see an issue that we are trying to fix with this PR.

**Comment by ranjanan** [comment]
All the pics are from the local conference, I want one from the previous global too.

**Comment by KeithWM** [comment]
I have to say I am a bit dismayed at how this PR has been handled. I would have appreciated at least someone having the chance to respond to your comment before the PR being merged.

**Comment by ranjanan** [comment]
@KeithWM I hope you can understand the sense of urgency here as the conference is coming up in a week. I appreciate the feedback as well, however, we absolutely need atleast a picture from the global conference from last year to be in one of those columns. The other three were from the JuliaCon local last year.

**Pull request merged**
