### PR TITLE
Add ticket links

### PR DESCRIPTION
**Pull request by MaxxxvD**
I don't really like how it currently looks, but I'm not a designer, so I'm open to suggestions to improve it :)
image

### CODE REVIEW

**Comment by MaxxxvD** [comment]
@bvdmitri @mkitti @rayegun

**Review by mkitti — APPROVED** [review]

**Comment by rayegun** [comment]
Can it be the same width as the other blocks?

Otherwise lgtm

**Comment by rayegun** [comment]
Can it be the same width as the other blocks?

I think you can just remove the small text and just have the button 

Otherwise lgtm

**Comment by mkitti** [comment]
Merge this please. We can address the details in another pull request.

**Pull request merged**
