### PR TITLE
JuliaCon 2024 Eindhoven: add more information about the venue

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR addresses #471 

@cityjumper

### CODE REVIEW

**Comment by skygering** [comment]
I think it would be good to have a bit more accessibility information here, or at least a link to accessibility information about the stadium. I pinged Gareth to see if we could get that information from the stadium folks. Reading it right now, if I had a mobility impairment, I would feel like the venue/city was too "sporty" for me and that it wouldn't work for me to travel there. That is more a comment about what we should add rather than the quality of what is there now, which I think looks good.

**Comment by cityjumper** [comment]
@skygering I have asked the stadium for more information, they are going to send photos about it. I think @bvdmitri can close this one and when we get more info on accessibility we should update the site.

**Comment by skygering** [comment]
Sounds good to me! I just wanted to bring it up

**Comment by bvdmitri** [comment]
@skygering It is a great comment, I've added more information for individuals with a disability

**Comment by skygering** [comment]
This is fantastic! Thanks @bvdmitri! Looks great 😊

**Pull request merged**
