### PR TITLE
add visa info page

### PR DESCRIPTION
**Pull request by Roger-luo**
I think the website is pretty good so I don't have much to add here. I'll wait for other dei-outreach team members to review this PR.

cc: @skygering

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by bvdmitri** [comment]
@Roger-luo would it make sense to move this information in the newly created Venue page, instead of creating a separate tab in the header? Or we can use the sub-headers, wdyt?

**Comment by skygering** [comment]
It might make sense to put it on the venue page, with the rest of the travel information as a subheader.

We also will be making a DEI/Accessibility tab. It could fall under that tab, but I think it should also maybe be in travel.

**Comment by Roger-luo** [comment]
@skygering @bvdmitri I moved it to the venue page as the first section as I think it could be the first thing people may want to check before heading to the county.

**Comment by bvdmitri** [comment]
Great, thanks @Roger-luo

**Pull request merged**
