### PR TITLE
Update financial assistance page

### PR DESCRIPTION
**Pull request by xorJane**
@Bubblemelon Does this look alright? It seems like the special dots aren't rendering on the website.

### CODE REVIEW

**Comment by Bubblemelon** [comment]
@xorJane Thanks for bringing this up! This is what it looks like on my phone via Chrome and on my computer via Firefox.

What browser are you using to view the website? Do they show up as square boxes for you? Like this 🥰 ? If that's the case, I think the 3 dots are from a not very common version of Unicode. 

image
image

**Comment by xorJane** [comment]
They're so cute in your browsers. I know we talked about this on slack, but I wanted to share that I see

image

on safari and

image

on chrome, both from my mac.

Maybe this is just something odd on my end. @NHDaly @nassarhuda @kelly-shen what do you see?

**Comment by Bubblemelon** [comment]
For the sake of consistency, I think this is a reasonable merge. :smiley:

**Comment by NHDaly** [comment]
I see the same thing as Jane.

There are some alternative characters that might work? These seem to render fine on my mac:
- ∴ ([Therefore](https://unicode-table.com/en/2234/)): `&#8756;`
- ﮶    ([Arabic three dots above](https://unicode-table.com/en/FBB6/)): `&#64438;` (but watch out cause this is a right-to-left character, so spacing renders weirdly)

That said, I don't think either of those are great, so probably best to just make Jane's change, sadly

**Comment by xorJane** [comment]
Thanks both! I merged for now, but if you want to try another character go for it :)

**Pull request merged**
