### PR TITLE
Add first set of 2021 sponsors

### PR DESCRIPTION
**Pull request by aviks**
cc: @ranjanan

### CODE REVIEW

**Comment by crstnbr** [comment]
Tried it locally, looks like this

Screenshot 2021-02-25 at 09 13 13

Do you think it is worth trying to add a horizontal line (or similar) above the sponsors.? Similar to what we have for the footer on https://proceedings.juliacon.org .

**Comment by crstnbr** [comment]
```
~~~
<div style="height:10px;"></div>
<div class="container-fluid" style="border-top:3px solid black;padding-top:30px">
  <div class="container sponsors">
    <h1 align="center">Sponsors</h1>
~~~
```

Screenshot 2021-02-25 at 16 47 12


Don't love it but perhaps better than nothing?

**Comment by ranjanan** [comment]
I'm alright either way to be honest.

**Comment by ranjanan** [comment]
Thanks a lot Avik!

**Comment by ranjanan** [comment]
But thanks for the suggestion Carston! Perhaps as this list of sponsors grows, adding a line may look better.

**Pull request merged**
