### PR TITLE
migration to franklin

### PR DESCRIPTION
**Pull request by tlienart**
This is from the fork: https://github.com/tlienart/www.juliacon.org which can be visualised at https://tlienart.github.io/www.juliacon.org/

This changes most files so not sure how you want to go about it. What we did back in the day for the julialang site with @logankilpatrick was to "release" the current version (so that if shit hits the fan we can revert to it easily) then merge.

### CODE REVIEW

**Comment by aviks** [comment]
I see you have already pushed this to the [franklin](https://github.com/JuliaCon/www.juliacon.org/tree/franklin) . Let's forget about this PR and mark that branch as the main branch, and set up deployment from there?

**Comment by aviks** [comment]
Also, this repo is set to publish rom `master`, not `gh-pages`

**Comment by tlienart** [comment]
ah sorry I thought that's what you wanted me to do

if I understand correctly you want: 

* this branch becomes main branch; we don't merge it to anything
* it deploys its content to `master` as opposed to `gh-pages`

I've updated the `deploy.yml` to reflect that

**Comment by tlienart** [comment]
(I've cancelled the workflow until you're happy for this to go through)

**Comment by aviks** [comment]
Thanks a ton @tlienart . This was a mammoth effort. Really appreciate it.

**Comment by logankilpatrick** [comment]
+1 thank you @tlienart !!!

**Comment by giordano** [comment]
The "submit proposal" link now opens the alert "Coming Soon"

**Comment by tlienart** [comment]
thanks @giordano I forked the repo end of January and it looks like 3-4 commits happened since then; I'll adjust

**Pull request closed without merging**
