### PR TITLE
Add site favicon for years 2019, 2018 and 2017

### PR DESCRIPTION
**Pull request by Bubblemelon**
**Reason for not adding the favicon for years 2016, 2015 and 2014, in this PR**

Years 2014 to 2016, do not reference a layout template and would require linking the favicon in each of their html pages. 

I will open a new PR to address refactoring years 2016, 2015 and 2014 so that the head component can be referenced from a layout template.

Additionally, I've notice that `_layouts/default.html` seems to be the template for year 2016, but the html pages for 2016 do not reference this layout at all. @essenciary, could you perhaps shed some light on this matter?

Related issue: #166

### CODE REVIEW

**Comment by xorJane** [comment]
This is lovely!

**Comment by ViralBShah** [comment]
@Bubblemelon Thanks for the attention to detail. My suggestion is in general to merge away, and one can always revert if something breaks.

**Comment by xorJane** [comment]
Cheryl, do you have permission to merge? I'll merge for now!

**Comment by Bubblemelon** [comment]
Re: @ViralBShah Thanks for the feedback!

Re: @xorJane Thanks for going ahead with the merge. 

It's been a pretty busy week for me. I'll follow up with Adrian on Slack. :smiley:

**Pull request merged**
